name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/airbnb-backend:v${{ github.run_number }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/airbnb-backend:latest ./api
          docker push ${{ secrets.DOCKER_USERNAME }}/airbnb-backend:v${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/airbnb-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/airbnb-client:v${{ github.run_number }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/airbnb-client:latest ./client
          docker push ${{ secrets.DOCKER_USERNAME }}/airbnb-client:v${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/airbnb-client:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: DOCKER_USERNAME
          script: |
            cd ~/airbnb-app
            
            # Create .env file
            cat > .env << EOL
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            CLIENT_URL=${{ secrets.CLIENT_URL }}
            SECRET_ACCESS_TOKEN=${{ secrets.SECRET_ACCESS_TOKEN }}
            EOL

            # Ensure docker-compose.yml exists
            if [ ! -f docker-compose.yml ]; then
              echo "docker-compose.yml not found"
              exit 1
            fi

            # Pull and restart containers
            docker-compose down
            docker-compose pull
            docker-compose up -d